# Site settings
title: 奇思妙想
author: umi
email: 9@umi.cat
lang: zh-CN
description: "umi 的个人博客，记录关于加密货币、安全研究、iOS 越狱等方面的技术探索与思考。"
url: "https://umi.cat"
baseurl: ""
google_analytics: G-9QG9K8G8G3
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: yous/whiteglass

# Build settings
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

comments: true

giscus:
  repo: "umiiii/umiiii.github.io"
  repo_id: "MDEwOlJlcG9zaXRvcnkyMDE0MzQyMTc="
  category: "Announcements"
  category_id: "DIC_kwDODAGkac4C632H"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "1"
  input_position: "bottom"
  theme: "light"
  lang: "zh-CN"

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
